TRUNCATE TABLE countries ;

INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AF','AFGHANISTAN','AFN',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AL','ALBANIA','ALL',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('DZ','ALGERIA','DZD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AS','AMERICAN SAMOA','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AD','ANDORRA ','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AO','ANGOLA','AOA',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AI','ANGUILLA','XCD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AQ','ANTARCTICA','',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AG','ANTIGUA AND BARBUDA','XCD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AR','ARGENTINA','ARS',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AM','ARMENIA','AMD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AW','ARUBA','AWG',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AU','AUSTRALIA','AUD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AT','AUSTRIA','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AZ','AZERBAIJAN','AZM',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BS','BAHAMAS','BSD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BH','BAHRAIN','BHD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BD','BANGLADESH','BDT',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BB','BARBADOS','BBD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BY','BELARUS','BYR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BE','BELGIUM','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BZ','BELIZE','BZD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BJ','BENIN','XOF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BM','BERMUDA','BMD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BT','BHUTAN','INR',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BT','BHUTAN','BTN',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BO','BOLIVIA','BOB',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BO','BOLIVIA','BOV',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BA','BOSNIA AND HERZEGOVINA','BAM',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BW','BOTSWANA','BWP',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BV','BOUVET ISLAND','NOK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BR','BRAZIL','BRL',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('IO','BRITISH INDIAN OCEAN TERRITORY','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BN','BRUNEI DARUSSALAM','BND',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BG','BULGARIA','BGN',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BF','BURKINA FASO','XOF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('BI','BURUNDI','BIF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('KH','CAMBODIA','KHR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CM','CAMEROON','XAF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CA','CANADA','CAD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CV','CAPE VERDE','CVE',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('KY','CAYMAN ISLANDS','KYD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CF','CENTRAL AFRICAN REPUBLIC','XAF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TD','CHAD','XAF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CL','CHILE','CLP',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CL','CHILE','CLF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CN','CHINA','CNY',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CX','CHRISTMAS ISLAND','AUD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CC','COCOS (KEELING) ISLANDS','AUD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CO','COLOMBIA','COP',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CO','COLOMBIA','COU',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('KM','COMOROS','KMF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CG','CONGO','XAF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CD','CONGO, THE DEMOCRATIC REPUBLIC OF','CDF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CK','COOK ISLANDS','NZD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CR','COSTA RICA','CRC',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CI','COTE D''IVOIRE','XOF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('HR','CROATIA','HRK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CU','CUBA','CUP',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CY','CYPRUS','CYP',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CZ','CZECH REPUBLIC','CZK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('DK','DENMARK','DKK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('DJ','DJIBOUTI','DJF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('DM','DOMINICA','XCD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('DO','DOMINICAN REPUBLIC','DOP',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('EC','ECUADOR','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('EG','EGYPT','EGP',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SV','EL SALVADOR','SVC',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SV','EL SALVADOR','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GQ','EQUATORIAL GUINEA','XAF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('ER','ERITREA','ERN',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('EE','ESTONIA','EEK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('ET','ETHIOPIA','ETB',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('FK','FALKLAND ISLANDS (MALVINAS)','FKP',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('FO','FAROE ISLANDS','DKK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('FJ','FIJI','FJD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('FI','FINLAND ','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('FR','FRANCE','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GF','FRENCH GUIANA ','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('PF','FRENCH POLYNESIA','XPF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TF','FRENCH SOUTHERN TERRITORIES','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GA','GABON','XAF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GM','GAMBIA','GMD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GE','GEORGIA','GEL',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('DE','GERMANY','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GH','GHANA','GHC',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GI','GIBRALTAR','GIP',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GR','GREECE','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GL','GREENLAND','DKK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GD','GRENADA','XCD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GP','GUADELOUPE','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GU','GUAM','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GT','GUATEMALA','GTQ',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GN','GUINEA','GNF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GW','GUINEA-BISSAU','GWP',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GW','GUINEA-BISSAU','XOF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GY','GUYANA','GYD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('HT','HAITI','HTG',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('HT','HAITI','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('HM','HEARD ISLAND AND MCDONALD ISLANDS','AUD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('VA','HOLY SEE (VATICAN CITY STATE)','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('HN','HONDURAS','HNL',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('HK','HONG KONG','HKD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('HU','HUNGARY','HUF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('IS','ICELAND','ISK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('IN','INDIA','INR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('ID','INDONESIA','IDR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('IR','IRAN, ISLAMIC REPUBLIC OF','IRR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('IQ','IRAQ','IQD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('IE','IRELAND','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('IL','ISRAEL','ILS',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('IT','ITALY','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('JM','JAMAICA','JMD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('JP','JAPAN','JPY',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('JO','JORDAN','JOD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('KZ','KAZAKHSTAN','KZT',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('KE','KENYA','KES',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('KI','KIRIBATI','AUD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('KP','KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF','KPW',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('KR','KOREA, REPUBLIC OF','KRW',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('KW','KUWAIT','KWD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('KG','KYRGYZSTAN','KGS',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('LA','LAO PEOPLE''S DEMOCRATIC REPUBLIC','LAK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('LV','LATVIA','LVL',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('LB','LEBANON','LBP',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('LS','LESOTHO','ZAR',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('LS','LESOTHO','LSL',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('LR','LIBERIA','LRD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('LY','LIBYAN ARAB JAMAHIRIYA','LYD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('LI','LIECHTENSTEIN','CHF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('LT','LITHUANIA','LTL',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('LU','LUXEMBOURG','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MO','MACAO','MOP',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','MKD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MG','MADAGASCAR','MGA',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MG','MADAGASCAR','MGF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MW','MALAWI','MWK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MY','MALAYSIA','MYR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MV','MALDIVES','MVR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('ML','MALI','XOF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MT','MALTA','MTL',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MH','MARSHALL ISLANDS','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MQ','MARTINIQUE','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MR','MAURITANIA','MRO',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MU','MAURITIUS','MUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('YT','MAYOTTE','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MX','MEXICO','MXN',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MX','MEXICO','MXV',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('FM','MICRONESIA, FEDERATED STATES OF','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MD','MOLDOVA, REPUBLIC OF','MDL',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MC','MONACO','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MN','MONGOLIA','MNT',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MS','MONTSERRAT','XCD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MA','MOROCCO','MAD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MZ','MOZAMBIQUE','MZM',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MM','MYANMAR','MMK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('NA','NAMIBIA','ZAR',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('NA','NAMIBIA','NAD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('NR','NAURU','AUD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('NP','NEPAL','NPR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('NL','NETHERLANDS','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AN','NETHERLANDS ANTILLES','ANG',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('NC','NEW CALEDONIA','XPF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('NZ','NEW ZEALAND','NZD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('NI','NICARAGUA','NIO',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('NE','NIGER','XOF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('NG','NIGERIA','NGN',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('NU','NIUE','NZD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('NF','NORFOLK ISLAND','AUD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('MP','NORTHERN MARIANA ISLANDS','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('NO','NORWAY','NOK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('OM','OMAN','OMR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('PK','PAKISTAN','PKR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('PW','PALAU','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('PS','PALESTINIAN TERRITORY, OCCUPIED','',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('PA','PANAMA','PAB',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('PA','PANAMA','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('PG','PAPUA NEW GUINEA','PGK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('PY','PARAGUAY','PYG',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('PE','PERU','PEN',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('PH','PHILIPPINES','PHP',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('PN','PITCAIRN','NZD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('PL','POLAND','PLN',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('PT','PORTUGAL','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('PR','PUERTO RICO','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('QA','QATAR','QAR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('RE','REUNION','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('RO','ROMANIA','ROL',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('RU','RUSSIAN FEDERATION','RUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('RU','RUSSIAN FEDERATION','RUB',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('RW','RWANDA','RWF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SH','SAINT HELENA','SHP',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('KN','SAINT KITTS AND NEVIS','XCD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('LC','SAINT LUCIA','XCD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('PM','SAINT PIERRE AND MIQUELON','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('VC','SAINT VINCENT AND THE GRENADINES','XCD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('WS','SAMOA','WST',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SM','SAN MARINO','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('ST','SAO TOME AND PRINCIPE','STD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SA','SAUDI ARABIA','SAR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SN','SENEGAL','XOF',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CS','SERBIA & MONTENEGRO','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CS','SERBIA & MONTENEGRO','CSD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SC','SEYCHELLES','SCR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SL','SIERRA LEONE','SLL',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SG','SINGAPORE','SGD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SK','SLOVAKIA','SKK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SI','SLOVENIA','SIT',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SB','SOLOMON ISLANDS','SBD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SO','SOMALIA','SOS',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('ZA','SOUTH AFRICA','ZAR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GS','SOUTH GEORGIA & THE SOUTH SANDWICH ISLANDS','',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('ES','SPAIN','EUR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('LK','SRI LANKA','LKR',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SD','SUDAN','SDD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SR','SURINAME','SRD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SJ','SVALBARD AND JAN MAYEN','NOK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SZ','SWAZILAND','SZL',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SE','SWEDEN','SEK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('CH','SWITZERLAND','CHF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('SY','SYRIAN ARAB REPUBLIC','SYP',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TW','TAIWAN, PROVINCE OF CHINA','TWD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TJ','TAJIKISTAN','TJS',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TZ','TANZANIA, UNITED REPUBLIC OF','TZS',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TH','THAILAND','THB',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TL','TIMOR-LESTE','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TG','TOGO','XOF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TK','TOKELAU','NZD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TO','TONGA','TOP',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TT','TRINIDAD AND TOBAGO','TTD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TN','TUNISIA','TND',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TR','TURKEY','TRL',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TM','TURKMENISTAN','TMM',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TC','TURKS AND CAICOS ISLANDS','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('TV','TUVALU','AUD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('UG','UGANDA','UGX',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('UA','UKRAINE','UAH',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('AE','UNITED ARAB EMIRATES','AED',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('GB','UNITED KINGDOM','GBP',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('US','UNITED STATES','USD',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('US','UNITED STATES','USS',1,1);
-- INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('US','UNITED STATES','USN',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('UM','UNITED STATES MINOR OUTLYING ISLANDS','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('UY','URUGUAY','UYU',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('UZ','UZBEKISTAN','UZS',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('VU','VANUATU','VUV',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('VE','VENEZUELA','VEB',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('VN','VIET NAM','VND',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('VG','VIRGIN ISLANDS, BRITISH','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('VI','VIRGIN ISLANDS, U.S.','USD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('WF','WALLIS AND FUTUNA','XPF',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('EH','WESTERN SAHARA','MAD',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('YE','YEMEN','YER',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('ZM','ZAMBIA','ZMK',1,1);
INSERT INTO countries (id, name,currency_id ,created_by, modified_by ) values ('ZW','ZIMBABWE','ZWD',1,1);
