-- TRUNCATE TABLE currencies ;
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('AFN','Afghani','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('ALL','Lek','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('DZD','Algerian Dinar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('USD','US Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('EUR','Euro','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('AOA','Kwanza','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('XCD','East Carribbean Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('ARS','Argentine Peso','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('AMD','Armenian Dram','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('AWG','Aruban Guilder','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('AUD','Australian Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('AZM','Azerbaijanian Manat','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BSD','Bahamian Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BHD','Bahraini Dinar','3',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BDT','Taka','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BBD','Barbados Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BYR','Belarussian Ruble','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BZD','Belize Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('XOF','CFA Franc BCEAO','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BMD','Bermudian Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('INR','Indian Rupee','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BTN','Ngultrum','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BOB','Boliviano','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BOV','Mvdol','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BAM','Convertible Marks','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BWP','Pula','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('NOK','Norvegian Krone','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BRL','Brazilian Real','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BND','Brunei Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BGN','Bulgarian Lev','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('BIF','Burundi Franc','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('KHR','Riel','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('XAF','CFA Franc BEAC','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('CAD','Canadian Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('CVE','Cape Verde Escudo','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('KYD','Cayman Islands Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('CLP','Chilean Peso','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('CLF','Unidades de fomento','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('CNY','Yuan Renminbi','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('COP','Colombian Peso','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('COU','Unidad de Valor Real','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('KMF','Comoro Franc','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('CDF','Franc Congolais','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('NZD','New Zealand Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('CRC','Costa Rican Colon','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('HRK','Croatian kuna','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('CUP','Cuban Peso','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('CYP','Cyprus Pound','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('CZK','Czech Koruna','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('DKK','Danish Krone','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('DJF','Djibouti Franc','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('DOP','Dominican Peso','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('EGP','Egyptian Pound','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('SVC','El Salvador Colon','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('ERN','Nakfa','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('EEK','Kroon','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('ETB','Ethiopian Birr','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('FKP','Falkland Islands Pound','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('FJD','Fiji Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('XPF','CFP Franc','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('GMD','Dalasi','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('GEL','Lari','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('GHC','Cedi','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('GIP','Gibraltar Pound','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('GTQ','Quetzal','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('GNF','Guinea Franc','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('GWP','Guinea-Bissau Peso','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('GYD','Guyana Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('HTG','Gourde','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('HNL','Lempira','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('HKD','Hong Kong Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('HUF','Forint','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('ISK','Iceland Krona','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('IDR','Rupiah','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('IRR','Iranian Rial','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('IQD','Iraqi Dinar','3',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('ILS','New Israeli Sheqel','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('JMD','Jamaican Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('JPY','Yen','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('JOD','Jordanian Dinar','3',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('KZT','Tenge','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('KES','Kenyan Shilling','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('KPW','North Korean Won','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('KRW','Won','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('KWD','Kuwaiti Dinar','3',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('KGS','Som','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('LAK','Kip','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('LVL','Latvian Lats','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('LBP','Lebanese Pound','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('ZAR','Rand','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('LSL','Loti','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('LRD','Liberian Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('LYD','Lybian Dinar','3',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('CHF','Swiss Franc','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('LTL','Lithuanian Litas','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MOP','Pataca','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MKD','Denar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MGA','Ariary','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MGF','Malagasy Franc','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MWK','Kwacha','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MYR','Malaysian Ringgit','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MVR','Rufiyaa','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MTL','Maltese Lira','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MRO','Ouguiya','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MUR','Mauritius Rupee','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MXN','Mexican Peso','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MXV','Mexican Unidad de Inversion (UDI)','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MDL','Moldovan Leu','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MNT','Tugrik','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MAD','Moroccan Dirham','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MZM','Metical','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('MMK','Kyat','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('NAD','Namibia Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('NPR','Nepalese Rupee','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('ANG','Netherlands Antillan Guilder','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('NIO','Cordoba Oro','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('NGN','Naira','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('OMR','Rial Omani','3',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('PKR','Pakistan Rupee','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('PAB','Balboa','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('PGK','Kina','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('PYG','Guarani','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('PEN','Nuevo Sol','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('PHP','Philippine Peso','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('PLN','Zloty','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('QAR','Qatari Rial','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('ROL','Leu','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('RUR','Russian Ruble','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('RUB','Russian Ruble','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('RWF','Rwanda Franc','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('SHP','Saint Helena Pound','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('WST','Tala','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('STD','Dobra','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('SAR','Saudi Riyal','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('CSD','Serbian Dinar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('SCR','Seychelles Rupee','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('SLL','Leone','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('SGD','Singapore Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('SKK','Slovak Koruna','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('SIT','Tolar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('SBD','Solomon Islands Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('SOS','Somali Shilling','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('LKR','Sri Lanka Rupee','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('SDD','Sudanese Dinar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('SRD','Suriname Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('SZL','Lilangeni','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('SEK','Swedish Krona','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('SYP','Syrian Pound','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('TWD','New Taiwan Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('TJS','Somoni','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('TZS','Tanzanian Shilling','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('THB','Baht','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('TOP','Pa�anga','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('TTD','Trinidad and Tobago Dollar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('TND','Tunisian Dinar','3',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('TRL','Turkish Lira','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('TMM','Manat','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('UGX','Uganda Shilling','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('UAH','Hryvnia','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('AED','UAE Dirham','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('GBP','Pound Sterling','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('USS','US Dollar (Same day)','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('USN','US Dollar (Next day)','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('UYU','Peso Uruguayo','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('UZS','Uzbekistan Sum','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('VUV','Vatu','0',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('VEB','Bolivar','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('VND','Dong','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('YER','Yemeni Rial','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('ZMK','Kwacha','2',1,1);
INSERT INTO currencies (id, name,minor_unit,created_by, modified_by ) values ('ZWD','Zimbabwe Dollar','2',1,1);

